[target.'cfg(all(target_os = "linux", not(target_env = "musl")))']
rustflags = [
  "-C", "link-arg=-Wl,-E",
]

[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-arg=-Wl,-E",
]
